-- ============================================================
-- TurismoUQ - Modelo relacional normalizado (3FN)
-- Compatible con Oracle SQL Developer Data Modeler
-- ============================================================

-- ------------------------------------------------------------
-- Catálogos base
-- ------------------------------------------------------------

CREATE TABLE MUNICIPIO (
    municipio_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE TIPO_ALOJAMIENTO (
    tipo_alojamiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR2(50) NOT NULL UNIQUE
);

-- Entidad adicional: separa el rol del usuario para no repetirlo
-- como texto libre y permitir extenderlo (permisos) sin tocar USUARIO_SISTEMA.
CREATE TABLE ROL (
    rol_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR2(50) NOT NULL UNIQUE -- ADMINISTRADOR, ENCARGADO_ALOJAMIENTO
);

-- ------------------------------------------------------------
-- Alojamientos y habitaciones
-- ------------------------------------------------------------

CREATE TABLE ALOJAMIENTO (
    alojamiento_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id           NUMBER NOT NULL,
    tipo_alojamiento_id    NUMBER NOT NULL,
    nombre_comercial       VARCHAR2(150) NOT NULL,
    direccion              VARCHAR2(200) NOT NULL,
    calificacion_estrellas NUMBER(1) NOT NULL,
    telefono               VARCHAR2(30),
    correo                 VARCHAR2(100),
    CONSTRAINT fk_aloj_municipio FOREIGN KEY (municipio_id)
        REFERENCES MUNICIPIO(municipio_id),
    CONSTRAINT fk_aloj_tipo FOREIGN KEY (tipo_alojamiento_id)
        REFERENCES TIPO_ALOJAMIENTO(tipo_alojamiento_id),
    CONSTRAINT ck_aloj_estrellas CHECK (calificacion_estrellas BETWEEN 1 AND 5)
);

CREATE TABLE HABITACION (
    habitacion_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alojamiento_id    NUMBER NOT NULL,
    numero            VARCHAR2(10) NOT NULL,
    capacidad_maxima  NUMBER NOT NULL,
    tipo_habitacion   VARCHAR2(30) NOT NULL,
    descripcion       VARCHAR2(500),
    CONSTRAINT fk_hab_alojamiento FOREIGN KEY (alojamiento_id)
        REFERENCES ALOJAMIENTO(alojamiento_id),
    CONSTRAINT uq_hab_numero UNIQUE (alojamiento_id, numero),
    CONSTRAINT ck_hab_tipo CHECK (tipo_habitacion IN
        ('SENCILLA','DOBLE','SUITE','CABANA')),
    CONSTRAINT ck_hab_capacidad CHECK (capacidad_maxima > 0)
);

-- ------------------------------------------------------------
-- Temporadas y tarifas
-- ------------------------------------------------------------

CREATE TABLE TEMPORADA (
    temporada_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(100) NOT NULL,       -- ej: 'Semana Santa'
    categoria     VARCHAR2(10) NOT NULL,        -- ALTA, MEDIA, BAJA
    anio          NUMBER(4) NOT NULL,
    fecha_inicio  DATE NOT NULL,
    fecha_fin     DATE NOT NULL,
    CONSTRAINT ck_temp_categoria CHECK (categoria IN ('ALTA','MEDIA','BAJA')),
    CONSTRAINT ck_temp_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT uq_temp_nombre_anio UNIQUE (nombre, anio)
);

-- PK compuesta: el precio depende exactamente de la pareja
-- (habitacion, temporada), nada más.
CREATE TABLE TARIFA (
    habitacion_id NUMBER NOT NULL,
    temporada_id  NUMBER NOT NULL,
    precio_noche  NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_tarifa PRIMARY KEY (habitacion_id, temporada_id),
    CONSTRAINT fk_tarifa_hab FOREIGN KEY (habitacion_id)
        REFERENCES HABITACION(habitacion_id),
    CONSTRAINT fk_tarifa_temp FOREIGN KEY (temporada_id)
        REFERENCES TEMPORADA(temporada_id),
    CONSTRAINT ck_tarifa_precio CHECK (precio_noche > 0)
);

-- ------------------------------------------------------------
-- Clientes y reservas
-- ------------------------------------------------------------

CREATE TABLE CLIENTE (
    cliente_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150) NOT NULL,
    documento_identidad VARCHAR2(30) NOT NULL UNIQUE,
    correo              VARCHAR2(100) NOT NULL,
    telefono            VARCHAR2(30),
    ciudad_origen       VARCHAR2(100)
);

CREATE TABLE RESERVA (
    reserva_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id     NUMBER NOT NULL,
    fecha_checkin  DATE NOT NULL,
    fecha_checkout DATE NOT NULL,
    fecha_reserva  DATE DEFAULT SYSDATE NOT NULL,
    estado         VARCHAR2(15) NOT NULL,
    CONSTRAINT fk_reserva_cliente FOREIGN KEY (cliente_id)
        REFERENCES CLIENTE(cliente_id),
    CONSTRAINT ck_reserva_estado CHECK (estado IN
        ('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA')),
    CONSTRAINT ck_reserva_fechas CHECK (fecha_checkout > fecha_checkin)
);

-- Asociativa: una reserva puede cubrir varias habitaciones,
-- cada una con su propio rango de fechas dentro del grupo.
CREATE TABLE RESERVA_HABITACION (
    reserva_habitacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id            NUMBER NOT NULL,
    habitacion_id         NUMBER NOT NULL,
    fecha_checkin         DATE NOT NULL,
    fecha_checkout        DATE NOT NULL,
    CONSTRAINT fk_reshab_reserva FOREIGN KEY (reserva_id)
        REFERENCES RESERVA(reserva_id),
    CONSTRAINT fk_reshab_habitacion FOREIGN KEY (habitacion_id)
        REFERENCES HABITACION(habitacion_id),
    CONSTRAINT ck_reshab_fechas CHECK (fecha_checkout > fecha_checkin),
    CONSTRAINT uq_reshab UNIQUE (reserva_id, habitacion_id, fecha_checkin)
);

-- ------------------------------------------------------------
-- Pagos
-- ------------------------------------------------------------

CREATE TABLE PAGO (
    pago_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id NUMBER NOT NULL,
    fecha_pago DATE DEFAULT SYSDATE NOT NULL,
    monto      NUMBER(10,2) NOT NULL,
    metodo     VARCHAR2(20) NOT NULL,
    estado     VARCHAR2(15) NOT NULL,
    CONSTRAINT fk_pago_reserva FOREIGN KEY (reserva_id)
        REFERENCES RESERVA(reserva_id),
    CONSTRAINT ck_pago_metodo CHECK (metodo IN
        ('TARJETA_CREDITO','TARJETA_DEBITO','PSE','TRANSFERENCIA','EFECTIVO')),
    CONSTRAINT ck_pago_estado CHECK (estado IN
        ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO')),
    CONSTRAINT ck_pago_monto CHECK (monto > 0)
);

-- ------------------------------------------------------------
-- Servicios complementarios
-- ------------------------------------------------------------

CREATE TABLE SERVICIO (
    servicio_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alojamiento_id NUMBER NOT NULL,
    nombre         VARCHAR2(100) NOT NULL,
    descripcion    VARCHAR2(500),
    precio         NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (alojamiento_id)
        REFERENCES ALOJAMIENTO(alojamiento_id),
    CONSTRAINT ck_servicio_precio CHECK (precio >= 0)
);

CREATE TABLE RESERVA_SERVICIO (
    reserva_servicio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id           NUMBER NOT NULL,
    servicio_id          NUMBER NOT NULL,
    cantidad             NUMBER NOT NULL,
    CONSTRAINT fk_resserv_reserva FOREIGN KEY (reserva_id)
        REFERENCES RESERVA(reserva_id),
    CONSTRAINT fk_resserv_servicio FOREIGN KEY (servicio_id)
        REFERENCES SERVICIO(servicio_id),
    CONSTRAINT uq_resserv UNIQUE (reserva_id, servicio_id),
    CONSTRAINT ck_resserv_cantidad CHECK (cantidad > 0)
);

-- ------------------------------------------------------------
-- Reseñas
-- ------------------------------------------------------------

-- reserva_id es UNIQUE: una reseña queda ligada a la reserva
-- completada que la origina (evita reseñas sin estadía real).
CREATE TABLE RESENA (
    resena_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id     NUMBER NOT NULL,
    alojamiento_id NUMBER NOT NULL,
    reserva_id     NUMBER NOT NULL,
    calificacion   NUMBER(1) NOT NULL,
    comentario     VARCHAR2(1000),
    fecha          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_resena_cliente FOREIGN KEY (cliente_id)
        REFERENCES CLIENTE(cliente_id),
    CONSTRAINT fk_resena_alojamiento FOREIGN KEY (alojamiento_id)
        REFERENCES ALOJAMIENTO(alojamiento_id),
    CONSTRAINT fk_resena_reserva FOREIGN KEY (reserva_id)
        REFERENCES RESERVA(reserva_id),
    CONSTRAINT ck_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5),
    CONSTRAINT uq_resena_reserva UNIQUE (reserva_id)
);

-- ------------------------------------------------------------
-- Usuarios internos de la plataforma
-- ------------------------------------------------------------

CREATE TABLE USUARIO_SISTEMA (
    usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id     NUMBER NOT NULL,
    nombre     VARCHAR2(150) NOT NULL,
    correo     VARCHAR2(100) NOT NULL UNIQUE,
    clave_hash VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id)
        REFERENCES ROL(rol_id)
);

-- Entidad adicional (asociativa): un encargado puede atender
-- uno o varios alojamientos; un administrador no necesita fila aquí.
CREATE TABLE USUARIO_ALOJAMIENTO (
    usuario_id     NUMBER NOT NULL,
    alojamiento_id NUMBER NOT NULL,
    CONSTRAINT pk_usuario_alojamiento PRIMARY KEY (usuario_id, alojamiento_id),
    CONSTRAINT fk_ua_usuario FOREIGN KEY (usuario_id)
        REFERENCES USUARIO_SISTEMA(usuario_id),
    CONSTRAINT fk_ua_alojamiento FOREIGN KEY (alojamiento_id)
        REFERENCES ALOJAMIENTO(alojamiento_id)
);
